/* -*- c-set-style: "K&R"; c-basic-offset: 8 -*-
 *
 * This file is generated by GitHub Copilot AI Coding Agent.
 * AI generated contents are NOT APPLICABLE for copyright.
 * However, this project as a whole is GPLv2+ as below.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 */

#ifndef FAKE_PID0_H
#define FAKE_PID0_H

#include "tracee/tracee.h"

/**
 * Check if the given tracee is the root tracee with fake_pid0 enabled.
 * Returns true if this tracee should see itself as PID 1.
 */
extern bool is_fake_pid0_root_tracee(const Tracee *tracee);

#endif /* FAKE_PID0_H */
