#!/bin/bash
# Build script for proot with glibc (static, aarch64)
# This file is generated by an AI coding agent (Github Copilot)
# AI generated contents are NOT APPLICABLE for copyright or warranty 
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-/tmp/proot-build-glibc}"

echo "=========================================="
echo "Building proot with glibc (static, aarch64)"
echo "=========================================="

# Install cross-compilation tools
echo "Installing cross-compilation tools..."
sudo apt-get update
sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
  qemu-user-static python3-dev wget

# Build talloc for glibc aarch64
echo "Building talloc for glibc aarch64..."
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

if [ ! -d "talloc-2.4.2" ]; then
  wget -q https://www.samba.org/ftp/talloc/talloc-2.4.2.tar.gz
  tar -xzf talloc-2.4.2.tar.gz
fi

cd talloc-2.4.2

# Create cross-answers file for talloc (minimal - let qemu run tests)
cat > cross-answers.txt << 'ANSWERS'
Checking uname sysname type: "Linux"
Checking uname machine type: "aarch64"
Checking uname release type: "5.0.0"
Checking uname version type: "1"
ANSWERS

CC=aarch64-linux-gnu-gcc \
  AR=aarch64-linux-gnu-ar \
  CFLAGS="-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE" \
  ./configure --prefix=/usr/local/talloc-aarch64 \
  --disable-python --disable-rpath \
  --cross-compile --cross-answers=cross-answers.txt \
  --cross-execute="qemu-aarch64-static -L /usr/aarch64-linux-gnu" \
  --bundled-libraries=talloc \
  --builtin-libraries=replace

# Build both static and shared
make -j$(nproc)
sudo make install

# Create static library from object files
echo "Creating static library..."
cd bin/default
sudo aarch64-linux-gnu-ar rcs /usr/local/talloc-aarch64/lib/libtalloc.a talloc*.o
cd ../..

# Build proot (without 32-bit loader for cross-compile)
echo "Building proot..."
cd "$REPO_ROOT/src"
make clean

# Override HAS_LOADER_32BIT since we're cross-compiling and don't have 32-bit toolchain
make CROSS_COMPILE=aarch64-linux-gnu- \
  CC=aarch64-linux-gnu-gcc \
  CFLAGS="-I/usr/local/talloc-aarch64/include -I$REPO_ROOT/src/compat" \
  LDFLAGS="-L/usr/local/talloc-aarch64/lib -static -ltalloc" \
  HAS_LOADER_32BIT=

# Verify
echo "Verifying build..."
file proot
ls -lh proot

# Verify architecture
if file proot | grep -q aarch64; then
  echo "✓ Successfully built aarch64 binary"
else
  echo "✗ ERROR: Not aarch64 binary"
  exit 1
fi

# Verify static linking
echo "Checking static linking..."
if ldd proot 2>&1 | grep -q "not a dynamic executable"; then
  echo "✓ Successfully built static binary"
elif ldd proot 2>&1 | grep -q "statically linked"; then
  echo "✓ Successfully built static binary"
else
  echo "⚠ Warning: Binary may not be fully static"
  ldd proot || true
fi

echo "=========================================="
echo "Build completed successfully!"
echo "Binary: $REPO_ROOT/src/proot"
echo "=========================================="
