#!/bin/bash
# Build script for proot with Android Bionic libc (dynamic, aarch64) in Termux
# This file is generated by an AI coding agent (GitHub Copilot)
# AI generated contents are NOT APPLICABLE for copyright or warranty 
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-/tmp/proot-build-android}"

: ${PREFIX:=/data/data/com.termux/files/usr}

echo "=========================================="
echo "Building proot with Android Bionic (dynamic, aarch64) in Termux"
echo "=========================================="

# Check if we're in Termux environment
if [ -d "/data/data/com.termux" ]; then
    echo "Running in Termux environment"
    IS_TERMUX=1
else
    echo "Not in Termux environment, assuming native aarch64"
    IS_TERMUX=0
fi

# Install build dependencies in Termux
if [ "$IS_TERMUX" = "1" ]; then
    echo "Installing build dependencies..."
    
    # Check if pkg is available
    if command -v pkg &> /dev/null; then
        # Update package lists with error handling
        echo "Updating package lists..."
        if pkg update -y 2>&1 | tee /tmp/pkg-update.log; then
            echo "Package update successful"
        else
            echo "WARNING: Package update failed. Trying to continue with existing packages..."
            cat /tmp/pkg-update.log | tail -20
        fi
        
        # Try to install packages
        echo "Installing required packages..."
        for package in clang make wget python git; do
            if command -v $package &> /dev/null || command -v ${package/-*/} &> /dev/null; then
                echo "✓ $package already available"
            else
                echo "Installing $package..."
                if pkg install -y $package 2>&1 | tee /tmp/pkg-install-$package.log; then
                    echo "✓ $package installed"
                else
                    echo "⚠ WARNING: Could not install $package"
                    cat /tmp/pkg-install-$package.log | tail -10
                fi
            fi
        done
    else
        echo "ERROR: pkg command not found"
        exit 1
    fi
fi

# Verify essential tools are available
echo "Verifying build tools..."
if ! command -v clang &> /dev/null && ! command -v gcc &> /dev/null; then
    echo "ERROR: No C compiler found (tried clang and gcc)"
    echo "Please ensure build tools are installed in the Termux environment"
    exit 1
fi

# Use clang if available, otherwise gcc
if command -v clang &> /dev/null; then
    export CC=clang
    export AR=llvm-ar
    export RANLIB=llvm-ranlib
    export LD=clang
    export STRIP=llvm-strip
    export OBJCOPY=llvm-objcopy
    export OBJDUMP=llvm-objdump
else
    export CC=gcc
    export AR=ar
    export RANLIB=ranlib
    export LD=gcc
    export STRIP=strip
    export OBJCOPY=objcopy
    export OBJDUMP=objdump
fi

echo "Using compiler: $CC"
$CC --version | head -2

if ! command -v make &> /dev/null; then
    echo "ERROR: make not found"
    exit 1
fi

if ! command -v wget &> /dev/null; then
    echo "ERROR: wget not found"
    exit 1
fi

# Build talloc for Android aarch64
echo "Building talloc for Android aarch64..."
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

if [ ! -d "talloc-2.4.2" ]; then
  wget -q https://www.samba.org/ftp/talloc/talloc-2.4.2.tar.gz
  tar -xzf talloc-2.4.2.tar.gz
fi

cd talloc-2.4.2

# Build talloc with minimal configuration
echo "Configuring talloc..."
./configure --disable-python --prefix=/tmp/android-talloc > /dev/null 2>&1 || true

# Now manually compile for Android aarch64 natively
echo "Compiling talloc for Android aarch64..."
mkdir -p /tmp/android-talloc/{lib,include}

# Create a minimal config header in the right location
mkdir -p lib/replace
cat > lib/replace/config.h << 'EOF'
/* Basic headers */
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_STRING_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDARG_H 1
#define HAVE_LIMITS_H 1
#define HAVE_DLFCN_H 1

/* Boolean type */
#define HAVE_BOOL 1

/* Types that system provides */
#define HAVE_INTPTR_T 1
#define HAVE_UINTPTR_T 1  
#define HAVE_PTRDIFF_T 1
#define HAVE_USECONDS_T 1
#define HAVE_TYPE_USECONDS_T 1

/* Talloc version */
#define TALLOC_BUILD_VERSION_MAJOR 2
#define TALLOC_BUILD_VERSION_MINOR 4
#define TALLOC_BUILD_VERSION_RELEASE 2

/* Functions - use system versions, not replacements */
#define HAVE_MMAP 1
#define HAVE_VA_COPY 1
#define HAVE_C99_VSNPRINTF 1
#define HAVE_MEMALIGN 1
#define HAVE_USLEEP 1
#define HAVE_VSNPRINTF 1
#define HAVE_SNPRINTF 1
#define HAVE_MEMMOVE 1
#define HAVE_STRNLEN 1
#define HAVE_MEMSET 1

/* Android doesn't have RTLD_DEFAULT in bionic before API 23 */
#ifndef RTLD_DEFAULT
#define RTLD_DEFAULT ((void*)0)
#endif
EOF

$CC -c -O2 -I. -Ilib/replace \
  -D__STDC_WANT_LIB_EXT1__=1 \
  -D_FILE_OFFSET_BITS=64 \
  talloc.c -o talloc.o

if [ ! -f talloc.o ]; then
  echo "ERROR: Failed to compile talloc.o"
  exit 1
fi

# Create static library
$AR rcs /tmp/android-talloc/lib/libtalloc.a talloc.o
$RANLIB /tmp/android-talloc/lib/libtalloc.a

# Copy header
cp talloc.h /tmp/android-talloc/include/

echo "Talloc library built successfully"
ls -lh /tmp/android-talloc/lib/libtalloc.a

# Build proot
echo "Building proot..."
cd "$REPO_ROOT/src"
make clean

# Build proot with loader for Android
echo "Building proot with loader for Android aarch64..."

make \
  CC="$CC" \
  AR="$AR" \
  LD="$LD" \
  STRIP="$STRIP" \
  OBJCOPY="$OBJCOPY" \
  OBJDUMP="$OBJDUMP" \
  HAS_LOADER_32BIT= \
  CFLAGS="-I/tmp/android-talloc/include -I$REPO_ROOT/src/compat" \
  LDFLAGS="-L/tmp/android-talloc/lib -ltalloc" \
  proot

# Verify
echo "Verifying build..."
file proot
ls -lh proot

# Verify architecture
if file proot | grep -q aarch64; then
  echo "✓ Successfully built aarch64 binary"
else
  echo "✗ ERROR: Not aarch64 binary"
  exit 1
fi

echo "=========================================="
echo "Build completed successfully!"
echo "Binary: $REPO_ROOT/src/proot"
echo "=========================================="
