#!/bin/bash
# Build script for proot with Android Bionic libc (static, aarch64)
# This file is generated by an AI coding agent (Github Copilot)
# AI generated contents are NOT APPLICABLE for copyright or warranty 
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-/tmp/proot-build-android-static}"

echo "=========================================="
echo "Building proot with Android Bionic (static, aarch64)"
echo "=========================================="

# Check for Android NDK
if [ -z "$ANDROID_NDK_HOME" ]; then
  echo "ERROR: ANDROID_NDK_HOME not set"
  exit 1
fi

echo "Using Android NDK: $ANDROID_NDK_HOME"

# Install build dependencies
echo "Installing build dependencies..."
sudo apt-get update
sudo apt-get install -y python3-dev wget

# Build talloc for Android aarch64 (static)
echo "Building talloc for Android aarch64 (static)..."
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

if [ ! -d "talloc-2.4.2" ]; then
  wget -q https://www.samba.org/ftp/talloc/talloc-2.4.2.tar.gz
  tar -xzf talloc-2.4.2.tar.gz
fi

cd talloc-2.4.2

# Setup Android NDK environment
export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
export TARGET=aarch64-linux-android
export API=21
export CC=$TOOLCHAIN/bin/$TARGET$API-clang
export AR=$TOOLCHAIN/bin/llvm-ar
export RANLIB=$TOOLCHAIN/bin/llvm-ranlib

# Build talloc with minimal configuration
# First configure natively to generate config files
echo "Configuring talloc..."
./configure --disable-python --prefix=/tmp/android-talloc-static > /dev/null 2>&1 || true

# Now manually compile for Android
echo "Compiling talloc for Android aarch64 (static)..."
mkdir -p /tmp/android-talloc-static/{lib,include}

# Create a minimal config header in the right location
mkdir -p lib/replace
cat > lib/replace/config.h << 'EOF'
/* Basic headers */
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_STRING_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDARG_H 1
#define HAVE_LIMITS_H 1
#define HAVE_DLFCN_H 1

/* Boolean type */
#define HAVE_BOOL 1

/* Types that system provides */
#define HAVE_INTPTR_T 1
#define HAVE_UINTPTR_T 1  
#define HAVE_PTRDIFF_T 1
#define HAVE_USECONDS_T 1
#define HAVE_TYPE_USECONDS_T 1

/* Talloc version */
#define TALLOC_BUILD_VERSION_MAJOR 2
#define TALLOC_BUILD_VERSION_MINOR 4
#define TALLOC_BUILD_VERSION_RELEASE 2

/* Functions - use system versions, not replacements */
#define HAVE_MMAP 1
#define HAVE_VA_COPY 1
#define HAVE_C99_VSNPRINTF 1
#define HAVE_MEMALIGN 1
#define HAVE_USLEEP 1
#define HAVE_VSNPRINTF 1
#define HAVE_SNPRINTF 1
#define HAVE_MEMMOVE 1
#define HAVE_STRNLEN 1
#define HAVE_MEMSET 1

/* Android doesn't have RTLD_DEFAULT in bionic before API 23 */
#ifndef RTLD_DEFAULT
#define RTLD_DEFAULT ((void*)0)
#endif
EOF

$CC -c -O2 -I. -Ilib/replace \
  -D__STDC_WANT_LIB_EXT1__=1 \
  -D_FILE_OFFSET_BITS=64 \
  talloc.c -o talloc.o 2>&1 | head -50

if [ ! -f talloc.o ]; then
  echo "ERROR: Failed to compile talloc.o"
  # Show full error
  $CC -c -O2 -I. -Ilib/replace \
    -D__STDC_WANT_LIB_EXT1__=1 \
    -D_FILE_OFFSET_BITS=64 \
    talloc.c -o talloc.o
  exit 1
fi

# Create static library
$AR rcs /tmp/android-talloc-static/lib/libtalloc.a talloc.o
$RANLIB /tmp/android-talloc-static/lib/libtalloc.a

# Copy header
cp talloc.h /tmp/android-talloc-static/include/

echo "Talloc library built successfully"
ls -lh /tmp/android-talloc-static/lib/libtalloc.a

# Build proot
echo "Building proot (static)..."
cd "$REPO_ROOT/src"
make clean

export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
export TARGET=aarch64-linux-android
export API=21
export CC=$TOOLCHAIN/bin/$TARGET$API-clang
export AR=$TOOLCHAIN/bin/llvm-ar
export LD=$TOOLCHAIN/bin/$TARGET$API-clang
export STRIP=$TOOLCHAIN/bin/llvm-strip
export OBJCOPY=$TOOLCHAIN/bin/llvm-objcopy
export OBJDUMP=$TOOLCHAIN/bin/llvm-objdump
export CROSS_COMPILE=aarch64-linux-android-

# Build proot with loader for Android (static)
echo "Building proot with loader for Android aarch64 (static)..."

make \
  CC="$CC" \
  AR="$AR" \
  LD="$LD" \
  STRIP="$STRIP" \
  OBJCOPY="$OBJCOPY" \
  OBJDUMP="$OBJDUMP" \
  HAS_LOADER_32BIT= \
  CFLAGS="-I/tmp/android-talloc-static/include -I$REPO_ROOT/src/compat" \
  LDFLAGS="-L/tmp/android-talloc-static/lib -ltalloc -static" \
  proot

# Verify
echo "Verifying build..."
file proot
ls -lh proot

# Verify architecture
if file proot | grep -q aarch64; then
  echo "✓ Successfully built aarch64 binary"
else
  echo "✗ ERROR: Not aarch64 binary"
  exit 1
fi

# Verify static linking
echo "Checking static linking..."
if file proot | grep -q "statically linked"; then
  echo "✓ Successfully built static binary"
else
  echo "⚠ Warning: Binary may not be fully static"
  file proot
fi

echo "=========================================="
echo "Build completed successfully!"
echo "Binary: $REPO_ROOT/src/proot"
echo "=========================================="
