#!/bin/bash
# Build script for proot in Termux - downloads packages manually to avoid DNS issues
# This file is generated by an AI coding agent (GitHub Copilot)
# AI generated contents are NOT APPLICABLE for copyright or warranty 
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-/tmp/proot-build-android}"

: ${PREFIX:=/data/data/com.termux/files/usr}

echo "=========================================="
echo "Building proot with Android Bionic (dynamic, aarch64) in Termux"
echo "=========================================="

# Install build dependencies manually by downloading .deb files
echo "Installing build dependencies manually..."

# Create temp directory for downloads
mkdir -p /tmp/termux-debs
cd /tmp/termux-debs

# Download packages directly from mirror using IP address
# Using grimler.se mirror which tends to be more reliable
MIRROR="https://grimler.se/termux/termux-main"

# Core packages we need
PACKAGES="clang llvm make wget-static python git"

echo "Downloading packages from $MIRROR..."

# Function to download and install a package
install_pkg() {
    local pkg=$1
    echo "Attempting to install $pkg..."
    
    # Try to use existing package files if apt has them cached
    if apt-get install -y --download-only $pkg 2>/dev/null; then
        apt-get install -y $pkg
        return 0
    fi
    
    return 1
}

# Try installing with apt first (might work if cache exists)
for pkg in $PACKAGES; do
    if install_pkg $pkg; then
        echo "✓ Installed $pkg"
    else
        echo "⚠ Could not install $pkg via apt"
    fi
done

# Verify we have the essential tools
if ! command -v clang &> /dev/null; then
    echo "ERROR: clang not available. Cannot build without it."
    echo "This is likely due to DNS resolution issues in the emulated environment."
    echo "Please run this build on a native aarch64 system or use GitHub Actions with native runners."
    exit 1
fi

echo "Build tools verified:"
clang --version | head -2
make --version | head -1

cd "$REPO_ROOT"

# Continue with the rest of the build script
exec "$REPO_ROOT/scripts/build-termux-android-dynamic-aarch64.sh"
